namespace WinrtServer
{
    struct Pos3 {
        Single x;
        Single y;
        Single z;
    };

    [default_interface]
    runtimeclass Programmer
    {
        Programmer();

        Int32 Motivation{ get; };
        void GiveCoffee();
        void WriteDocumentation();
        Pos3 Add(Pos3 a, Pos3 b);
    }
}
