import "oaidl.idl";
import "ocidl.idl";
import "IRoyalPython.idl";
import "IHen.idl";
import "IDog.idl";
import "IPostman.idl";
import "IPetShop.idl";
import "IListener.idl";

[
	uuid(8edbf75d-ecf2-4a1f-affc-07fcb8dee00a),
	version(1.0),
]
library Interfaces
{
	interface IRoyalPython;
	interface IHen;
	interface IAsyncCluckObserver;
	interface IDog;
	interface IPostman;
	interface IPetShop;
	interface IListener;
	dispinterface _DPetShopEvents;
};

