import "oaidl.idl";
import "ocidl.idl";
import "IDog.idl";
import "IHen.idl";

typedef struct {
	BSTR Street;
	BSTR PostalCode;
	BSTR City;
} Address;

[
	oleautomation,
	object,
	uuid(7ea81732-10b2-4d8d-88f7-3c73f552dc39),
	pointer_default(unique)
]
interface IPetShop : IUnknown
{
	HRESULT BuyDog([out, retval] IDog** dog);
	HRESULT GetAddress([out, retval] Address* address);
};